require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'deepwall' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'deepwallTests' do
    inherit! :complete
    # Pods for testing
  end

  use_frameworks!
end

target 'deepwall-tvOS' do
  # Pods for deepwall-tvOS

  target 'deepwall-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
